$(function () {


        $('#table-sparkline').tablesorter(); 

     $("#search").keyup(function(){
        _this = this;
        // Show only matching TR, hide rest of them
        $.each($("#table-sparkline tbody").find("tr"), function() {
            console.log($(this).text());
            if($(this).text().toLowerCase().indexOf($(_this).val().toLowerCase()) == -1)
               $(this).hide();
            else
                 $(this).show();                
        });
    }); 

        $('#container').highcharts({
            chart: {
                type: 'bar'
            },
            title: {
                text: 'Firms Ranked By Growth (Lawyers and Partners)'
            },
            xAxis: {
                categories: ['Schiff Hardin',
'Miles & Stockbridge',
'Quinn Emanuel',
'Ogletree Deakins',
'Ballard Spahr',
'Wilson Sonsini',
'Littler Mendelson',
'Rees Broome',
'Sheppard Mullin',
'Oblon Spivak',
'Williams & Connolly',
'Morrison & Foerster',
"Cozen O'Connor",
'Banner & Witcoff',
'Gibson Dunn',
'Paul Weiss',
'Proskauer Rose',
'Pillsbury Winthrop',
'Paley Rothman',
'Hughes Hubbard',
'Thompson Coburn',
'Morrison & Foerster',
'Olsson Frank',
'Dechert',
'Gilbert',
'Vinson & Elkins',
'Cleary Gottlieb',
'McKenna Long',
'McGuireWoods',
'Winston & Strawn',
'Sterne Kessler',
'Sullivan & Cromwell',
'Baker & McKenzie',
'Baker & Hostetler',
'Caplin & Drysdale',
'Jackson Lewis',
'Milbank Tweed',
'Rothwell Figg',
'Mayer Brown',
'Kelley Drye',
'Jones Day',
'Oliff',
'McDermott Will',
'Holland & Knight',
'Chadbourne & Parke',
'Beveridge & Diamond',
'Latham & Watkins',
'Nixon Peabody',
'Venable',
'Miller & Chevalier',
'Fish & Richardson',
'King & Spalding',
'Hogan Lovells',
'Covington & Burling',
'Holland & Knight',
'Wiley Rein',
'Perkins Coie',
'Sutherland Asbill',
'Venable',
'Fried Frank',
'Morgan Lewis',
'Jenner & Block',
'Shulman Rogers',
'Hollingsworth',
'Groom Law Group',
'Foley Hoag',
'Buchanan Ingersoll',
'Greenberg Traurig',
'Odin, Feldman',
'Sidley Austin',
'Arnold & Porter',
'K&L Gates',
'Cooley',
'Kirkland & Ellis',
'Akin Gump',
'Crowell & Moring',
'Hogan Lovells',
'Pepper Hamilton',
'Cadwalader',
'Reed Smith',
'Drinker Biddle',
'Nixon & Vanderhye',
'Paul Hastings',
'Orrick',
'Van Ness Feldman',
'Skadden',
'Pillsbury Winthrop',
'Baker Botts',
'Arent Fox',
'Zuckerman Spaeder',
'Wilkinson Barker',
'Bracewell & Giuliani',
'Seyfarth Shaw',
'McGuireWoods',
'Linowes and Blocher',
'Foley & Lardner',
'Steptoe & Johnson LLP',
'Wilmer',
'Clifford Chance',
'Squire Sanders',
'Blank Rome',
'Stein Sperling',
'Thompson Hine',
'Greenberg Traurig',
'Duane Morris',
'Cohen Milstein',
'Bean Kinney',
'Lerch Early',
'Mintz Levin',
'Kilpatrick Townsend',
'Hunton & Williams',
'Keller and Heckman',
'Reed Smith',
'Kenyon & Kenyon',
'Buchanan Ingersoll',
'DLA Piper',
'Bryan Cave',
'Dentons',
'Cooley',
'Finnegan Henderson',
'Andrews Kurth',
'Baker Donelson',
'Goodwin Procter',
'Patton Boggs',
"O'Melveny & Myers",
'Ropes & Gray',
'Finnegan Henderson',
'Hunton & Williams',
'Krooth & Altman',
'Watt, Tieder, Hoffar & Fitzgerald',
'BuckleySandler',
'Manatt Phelps',
'Norton Rose',
'Weil Gotshal',
'Bingham McCutchen',
'Dickstein Shapiro',
'White & Case'
],
                title: {
                    text: null
                }
            },
            yAxis: {
                min: -30,
                max: 70,
                title: {
                    enabled:false
                },
                labels: {
                    overflow: 'justify',
                    formatter: function(){
                        return this.value + '%';
                    }
                }
            },
            tooltip: {
                formatter: function(){
                    return '<b>'+ this.point.category +'</b><br/>'+
                        this.point.y + '%';
                }
            },
            plotOptions: {
                bar: {
 dataLabels: {
                        enabled: true,
                        formatter: function() {
                            return this.y + '%';
                        },
                        inside: false,
                        padding: 10,
                        y: -1
                    }
                }
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'top',
                x: -40,
                y: 100,
                floating: true,
                borderWidth: 1,
                backgroundColor: (Highcharts.theme && Highcharts.theme.legendBackgroundColor || '#FFFFFF'),
                shadow: true
            },
            credits: {
                enabled: false
            },
            series: [{
                name: '',
                data: [66,
47,
46,
35,
21,
20,
19,
15,
14,
14,
13,
13,
11,
11,
11,
11,
11,
11,
10,
10,
9,
9,
8,
8,
8,
7,
7,
6,
6,
6,
6,
6,
6,
6,
5,
5,
5,
5,
5,
4,
3,
3,
3,
3,
3,
3,
2,
2,
2,
2,
2,
2,
2,
2,
2,
1,
1,
1,
1,
0,
0,
0,
0,
0,
0,
0,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-1,
-2,
-2,
-2,
-2,
-2,
-2,
-3,
-3,
-3,
-3,
-3,
-3,
-3,
-4,
-4,
-4,
-4,
-4,
-4,
-5,
-5,
-5,
-5,
-5,
-5,
-5,
-6,
-6,
-6,
-6,
-6,
-7,
-7,
-7,
-7,
-7,
-8,
-8,
-8,
-8,
-8,
-9,
-9,
-9,
-9,
-9,
-10,
-10,
-11,
-11,
-11,
-12,
-13,
-14,
-14,
-15,
-18,
-20,
-22,
-26
]
        }]
    });
});